### ISSUE TITLE
[biocswirl][WIP] Add introductory lessons

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#19]
# [biocswirl][WIP] Add introductory lessons

# Tasks 
- [x] map out course structure for bioconductor course 
- [ ] map out course structure for r basics course 
- [ ] complete lessons for bioconductor_basics
- [ ] complete lessons for r_basics 

# Resources
https://github.com/BrunoGrandePhD/MBB343
   http://manuals.bioinformatics.ucr.edu/home/R_BioCondManual
   https://bioinformatics-core-shared-training.github.io/cruk-autumn-school-2017/Introduction/bioc-intro.nb.html#about_the_bioconductor_project
   https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/
   http://people.duke.edu/~ccc14/duke-hts-2018/janice/3_IntroductionToR.html
https://github.com/swirldev/swirl_courses   

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
