### ISSUE TITLE
[refactor] [WIP] Prepare BiocSwirl for CRAN

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#2]
# [refactor] [WIP] Prepare BiocSwirl for CRAN

# Tasks 
- [ ] rewrite package using usethis() process 
- [ ] rewrite/complete vignette 
- [ ] test custom R functions 
- [ ] pass first CRAN check
- [x] Complete Dummy/Skeleton Course index 

# Course Material
- [ ] Add standard tutorial chapters (data import, practices, R basics, packages, etc) 
- [ ] Complete Low Level Analyses Section
- [ ] Complete High Level Analyses Section

# Resources

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
