### ISSUE TITLE
 [biocswirl] Convert MBB343 into BiocSwirl Course 

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#23]
# [biocswirl] Convert MBB343 into BiocSwirl Course 

# Tasks 
- [x] Prioritize lessons to convert to yaml
- [ ] Convert to biocswirl standalone course

## Lessons
- [x] Lab 01 - Getting Started with R and RStudio
- [ ] Lab 02 - Data Structures in R
- [ ] Lab 03 - Data Exploration: Introducing the Tidyverse
- [ ] Lab 04 - Data Wrangling: Taming Your Data
- [ ] Lab 05 - Data Visualization: At Least 1,000 Words

# Resources
https://github.com/BrunoGrandePhD/MBB343

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
