### ISSUE TITLE
[biocswirl] Convert second part of mbb course into "Intro to Stats" BiocSwirl course

### ISSUE THREAD

**Issue by juliaphilipp** [biocswirl-dev-team/BiocSwirl#28]
# [biocswirl] Convert second part of mbb course into "Intro to Stats" BiocSwirl course

# Tasks
- [ ] Convert MBB course lessons to biocswirl lessons

# Lessons
- [ ] Lab 06 - Correlation and Two-Sample Tests
- [ ] Lab 07 - Categorical Tests and Multiple Hypothesis Testing
- [ ] Lab 08 - Simple Linear Regression
- [ ] Lab 09 - Multiple Linear Regression and Principal Component Analysis
- [ ] Lab 10 - Logistic Regression
- [ ] Lab 11 - Random Forest Classification
- [ ] Lab 12 - Hierarchical Clustering
- [ ] Lab 13 - Dealing with High-Dimensional Data: Non-linear Perspectives

# Resources
https://github.com/BrunoGrandePhD/MBB343
https://github.com/biocswirl-dev-team/BiocSwirl/blob/intro_to_stats/courses/intro_to_stats/session_contents.md

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
