### ISSUE TITLE
[biocswirl] Complete Bioconductor scRNA-seq course

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#6]
# [biocswirl] Complete scRNA-seq course

# Tasks 
 (GSE71585 dataset):
- [ ] [Low Level Analyses](biocswirl_package/courses/scrna_seq/lessons/low_level/low_level.yaml)   
- [ ] Importing, raw data preprocessing   
- [ ] Alignment  
- [ ] Quality Control   
- [ ] Normalization (with and without spike-ins)  
- [ ] Dimensionality Reduction  
- [ ] Correcting for batch effects  
- [ ] [High Level Analyses](biocswirl_package/courses/scrna_seq/lessons/high_level/high_level.yaml)  
- [ ] Clustering methods, exploratory analyses    
- [ ] Cell cycle phase classification from gene expression data  
- [ ] HVG and marker gene identification  
- [ ] Visualizations for high-throughput data

#Additional Resources
https://github.com/crazyhottommy/getting-started-with-genomics-tools-and-resources
https://girke.bioinformatics.ucr.edu/GEN242/mydoc_systemPipeRNAseq_02.html\
http://linnarssonlab.org/cortex/

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)

**Comment by lisancao** [comment]
UPDATE: 

If this course wants to be developed using another dataset that is OK. Some references that may be useful: 

Tutorials:
https://scrnaseq-course.cog.sanger.ac.uk/website/index.html
https://github.com/hemberg-lab/scRNA.seq.course/
https://tess.elixir-europe.org/materials/single-cell-rna-seq-data-analysis-with-r

Background:
https://www.embopress.org/doi/10.15252/msb.20188746
https://www.frontiersin.org/articles/10.3389/fcell.2018.00108/full

**Comment by souravsingh** [comment]
@lisancao Is the issue open to work? I believe some of the stuff in the checklist has been completed.

**Comment by lisancao** [comment]
@souravsingh Yes it is! Even though we have some lessons in there already there are still some more stuff to add, such as a lesson on Seurat. Since you worked on it before, would it be okay that I assign this issue to you? :)

**Comment by souravsingh** [comment]
Yes, I can work on the issue.
