### ISSUE TITLE
[biocswirl] Complete Bioconductor ChIP-seq Course

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#8]
# [biocswirl] Complete Bioconductor ChIP-seq Course

# Tasks 
- [ ] Biology of ChIP-seq 
- [x] Prepare data files*
- [x] Input data / data clean lesson
- [x] Trimming and QA filtering lesson
- [x] Sequence Alignment lesson
- [x] Quality Check lesson
- [x] Peak Calling lesson
- [x] Annotate Peaks lesson
- [ ] Comparison Lesson

*must be able to run locally on at least 8GB ram

# Additional Resources
https://github.com/crazyhottommy/getting-started-with-genomics-tools-and-resources
https://github.com/lisancao/Bioinformatics_with_R

It would be ideal to implement this pipeline: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5389943/

https://tess.elixir-europe.org/workflows/fork-of-chip-seq-workflow-with-intermediate-data

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
